export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import KokoroWarm from '@/components/KokoroWarm';
import CoepStatusBadge from '@/components/CoepStatusBadge';

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        {/* Ensure default Agent Lee voice settings are present */}
        <script crossOrigin="anonymous" dangerouslySetInnerHTML={{ __html: `
          try {
            if (!localStorage.getItem('agentlee_voice')) {
              localStorage.setItem('agentlee_voice','am_michael');
            }
            if (!localStorage.getItem('agentlee_voice_speed')) {
              localStorage.setItem('agentlee_voice_speed','0.95');
            }
          } catch(e) {}
        ` }} />
        {/* Warm Kokoro runtime in the background */}
  <div id="kokoro-warm-target"></div>
  {process.env.NEXT_PUBLIC_SHOW_COEP_BADGE === '1' ? <CoepStatusBadge /> : null}
  {children}
      </body>
    </html>
  )
}
