name: Deploy Cloudflare Worker

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths: [ 'cf-proxy/**', '.github/workflows/deploy-worker.yml' ]

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Deploy Cloudflare Worker (placeholder)
        run: echo "Skipping worker deploy in placeholder workflow"

      - name: Instructions
        run: |
          echo "This repository includes a Cloudflare Worker under cf-proxy/."
          echo "To enable automated deploys, restore the wrangler-action step with CF_API_TOKEN and CF_ACCOUNT_ID."
          echo "This placeholder workflow intentionally contains no secret references to avoid IDE warnings."
