name: Deploy Vite Site to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Profitability Gate
        run: npm run profit:gate
        env:
          MIN_ROAS: 4
          MIN_LTV_CAC: 3
          MAX_CAC: 120
          MKTG_SNAPSHOT: ./data/snapshots/last.json

      - name: Build
        env:
          # Prefer environment secret used by Vite client. Fallback to alternative names if present.
          VITE_GEMINI_API_KEY: ${{ secrets.VITE_GEMINI_API_KEY || secrets.GEMINI_API_KEY || secrets.AGENT_LEE_X }}
          GEMINI_API_KEY:       ${{ secrets.GEMINI_API_KEY       || secrets.VITE_GEMINI_API_KEY || secrets.AGENT_LEE_X }}
          API_KEY:              ${{ secrets.GEMINI_API_KEY       || secrets.VITE_GEMINI_API_KEY || secrets.AGENT_LEE_X }}
        run: |
          npm run build
          cp dist/index.html dist/404.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
