name: Deploy Cloudflare Worker
on:
  push:
    branches: [ main ]
    paths: [ 'cf-proxy/**', '.github/workflows/deploy-worker.yml' ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions: { contents: read }
    steps:
      - uses: actions/checkout@v4
      - run: npm i -g wrangler
      - name: Publish Worker
        working-directory: cf-proxy
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CF_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: |
          echo "${GEMINI_API_KEY}" | wrangler secret put GEMINI_API_KEY --yes
          wrangler publish
